(() => {
  const portal = document.querySelector("#portal");
  const modal = document.querySelector("#depositModal");
  const token = location.pathname.split("/").filter(Boolean).pop();
  const esc = value => String(value ?? "").replace(/[&<>\"']/g, character => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character]);
  const money = value => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(Number(value) || 0);
  const bytes = value => value ? `${(Number(value) / 1000000).toFixed(1)} MB` : "Private file";
  let data;
  function totals() { const items = data.items || []; const subtotal = items.reduce((sum, item) => sum + Number(item.quantity || 0) * Number(item.unit_price || 0) * (1 - Number(item.discount || 0) / 100), 0); const estimate = data.estimate || {}; const discount = Number(estimate.discount_amount || 0), tax = Number(estimate.tax_amount || 0), shipping = Number(estimate.shipping_amount || 0), installation = Number(estimate.installation_amount || 0), fees = Number(estimate.additional_fees || 0), deposit = Number(estimate.deposit_required || 0); const grand = Math.max(0, subtotal - discount + tax + shipping + installation + fees); return { subtotal, discount, tax, shipping, installation, fees, deposit, grand, balance: Math.max(0, grand - deposit) }; }
  function render() {
    const estimate = data.estimate, customer = data.customer, project = data.project, total = totals();
    document.title = `${estimate.estimate_number} | Next Print NY`;
    portal.innerHTML = `<section class="customer-hero"><div><a href="/" class="back-link">← Next Print NY</a><p class="eyebrow">SECURE ESTIMATE</p><div class="estimate-heading"><h1>Estimate #${esc(estimate.estimate_number)}</h1><span class="customer-status">${esc(String(project.status || estimate.status).replace(/_/g, " "))}</span></div><p>${esc(estimate.project_title || "Your print project")}</p></div><div class="hero-actions"><button class="secondary" data-action="print">Download PDF</button><button class="primary" data-action="message">Send Message</button></div></section>
      <section class="customer-overview"><article><p class="eyebrow">PREPARED FOR</p><strong>${esc(customer.name)}</strong><span>${esc(customer.contact_name || "")}</span><span>${esc(customer.email || "")}</span></article><article><p class="eyebrow">ESTIMATE DETAILS</p><span>Created: <strong>${esc(estimate.estimate_date || "—")}</strong></span><span>Expires: <strong>${esc(estimate.expiration_date || "—")}</strong></span><span>Project: <strong>${esc(project.project_number)}</strong></span></article><article class="customer-total"><p>TOTAL ESTIMATE</p><strong>${money(total.grand)}</strong><span>USD</span></article><article><p class="eyebrow">PROJECT STATUS</p><div class="status-steps"><span class="is-active">Sent</span><span>Viewed</span><span>Approved</span><span>Paid</span></div></article></section>
      <section class="customer-layout"><div class="customer-main"><article class="customer-card"><div class="card-title"><div><p class="eyebrow">PRODUCTS & SERVICES</p><h2>${esc(estimate.project_title || "Estimate items")}</h2></div><span>${data.items.length} items</span></div><p class="project-description">${esc(estimate.project_description || "")}</p><div class="customer-items">${data.items.map(item => `<article><div class="item-thumb">${esc((item.title || "P").slice(0,1))}</div><div><strong>${esc(item.title)}</strong><span>${esc(item.description || "")}</span><small>${esc(String(item.quantity))} ${esc(item.unit || "each")} × ${money(item.unit_price)}</small></div><b>${money(Number(item.quantity) * Number(item.unit_price) * (1 - Number(item.discount || 0) / 100))}</b></article>`).join("")}</div><dl class="customer-summary"><div><dt>Subtotal</dt><dd>${money(total.subtotal)}</dd></div><div><dt>Discount</dt><dd>−${money(total.discount)}</dd></div><div><dt>Tax</dt><dd>${money(total.tax)}</dd></div><div><dt>Shipping</dt><dd>${money(total.shipping)}</dd></div><div><dt>Installation</dt><dd>${money(total.installation)}</dd></div><div><dt>Additional Fees</dt><dd>${money(total.fees)}</dd></div><div class="total"><dt>Grand Total</dt><dd>${money(total.grand)}</dd></div><div class="balance"><dt>Balance Due</dt><dd>${money(total.balance)}</dd></div></dl></article>
        <article class="customer-card"><p class="eyebrow">PROJECT DETAILS</p><h2>Production brief</h2><p class="detail-copy">${esc(estimate.project_details || "Project specifications will be confirmed by Next Print NY.")}</p></article>
        <article class="customer-card"><p class="eyebrow">TERMS & CONDITIONS</p><p class="detail-copy">${esc(estimate.terms || "Terms will be confirmed before production begins.")}</p></article></div>
        <aside class="customer-side"><article class="customer-card action-card"><p class="eyebrow">ACTIONS</p><button class="primary" data-decision="accepted">Accept Estimate</button><button class="secondary" data-decision="changes">Request Changes</button><button class="secondary danger" data-decision="rejected">Reject Estimate</button><button class="secondary" data-action="deposit">Pay Deposit · ${money(total.deposit)}</button></article><article class="customer-card"><div class="card-title"><div><p class="eyebrow">PROJECT FILES</p><h2>Shared files</h2></div></div><div class="file-tabs"><button class="is-active" data-file-source="next_print">From Next Print</button><button data-file-source="customer">From You</button></div><div id="customerFiles" class="customer-files"></div></article><article class="customer-card message-card"><p class="eyebrow">PROJECT MESSAGES</p><div id="messages" class="customer-messages">${(data.messages || []).map(message => `<p class="${message.sender_role === "customer" ? "mine" : "theirs"}">${esc(message.body)}</p>`).join("")}</div><form id="messageForm"><input name="message" maxlength="2000" placeholder="Write a message…" aria-label="Message"><button class="primary">Send</button></form><small>Written communication only. Everything stays on your project record.</small></article></aside></section>`;
    renderFiles("next_print");
  }
  function renderFiles(source) { const target = document.querySelector("#customerFiles"); if (!target) return; const files = (data.files || []).filter(file => file.source === source); target.innerHTML = files.length ? files.map(file => `<article><span>${esc((file.name || "File").split(".").pop().toUpperCase())}</span><div><strong>${esc(file.name)}</strong><small>${esc(file.status || "received")} · ${bytes(file.size_bytes)}</small></div><button type="button" title="Private download available after verification">↓</button></article>`).join("") : "<p class=\"empty-note\">No files shared yet.</p>"; }
  async function decision(decision) { const response = await fetch("/api/project-portal?action=decision", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ token, decision }) }); const result = await response.json().catch(() => ({})); if (!response.ok) return alert(result.error || "Could not update the estimate."); data.project.status = result.status; render(); }
  async function sendMessage(form) { const input = form.elements.message; const body = input.value.trim(); if (!body) return; const response = await fetch("/api/project-portal?action=message", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ token, body }) }); const result = await response.json().catch(() => ({})); if (!response.ok) return alert(result.error || "Message could not be sent."); data.messages.push(result.message); input.value = ""; render(); }
  function openDeposit() { const total = totals(); document.querySelector("#depositDetails").innerHTML = `<dt>Estimate</dt><dd>${esc(data.estimate.estimate_number)}</dd><dt>Deposit due</dt><dd>${money(total.deposit || total.balance)}</dd><dt>Project</dt><dd>${esc(data.estimate.project_title || data.project.project_number)}</dd>`; document.querySelector("#paymentStatus").textContent = ""; modal.showModal(); }
  async function reportDeposit() { const total = totals(); const proof = document.querySelector("#paymentProof").files[0]; const proofDataUrl = proof ? await new Promise(resolve => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.readAsDataURL(proof); }) : ""; const response = await fetch("/api/project-portal?action=payment", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ token, amount: total.deposit || total.balance, reference: document.querySelector("#paymentReference").value, proofName: proof?.name || "", proofDataUrl }) }); const result = await response.json().catch(() => ({})); document.querySelector("#paymentStatus").textContent = response.ok ? "Payment submitted. Status: Payment Pending Verification." : (result.error || "Payment submission failed."); if (response.ok) data.project.payment_status = "pending_verification"; }
  portal.addEventListener("click", event => { const button = event.target.closest("button"); if (!button) return; if (button.dataset.decision) decision(button.dataset.decision); if (button.dataset.action === "deposit") openDeposit(); if (button.dataset.action === "message") document.querySelector("#messageForm input")?.focus(); if (button.dataset.action === "print") window.print(); if (button.dataset.fileSource) { document.querySelectorAll("[data-file-source]").forEach(tab => tab.classList.toggle("is-active", tab === button)); renderFiles(button.dataset.fileSource); } });
  portal.addEventListener("submit", event => { if (event.target.id === "messageForm") { event.preventDefault(); sendMessage(event.target); } });
  document.querySelector("#depositForm").addEventListener("submit", event => { event.preventDefault(); reportDeposit(); });
  fetch(`/api/project-portal?token=${encodeURIComponent(token)}`).then(async response => { const result = await response.json(); if (!response.ok) throw new Error(result.error || "This secure portal is unavailable."); data = result; render(); }).catch(error => { portal.innerHTML = `<section class="customer-error"><h1>Secure portal unavailable</h1><p>${esc(error.message)}</p></section>`; });
})();
